language: node_js
node_js:
        - "5.11"

branches:
  only:
    - master

before_script:
        - npm install -g firebase-tools

script:
        - echo "Deploying!"
after_success:
        - firebase deploy --token=${FIREBASE_TOKEN}
